"""Condition evaluation engine for the brute-force scan.

This module is the core of the search phase. Given a dataframe enriched with
technical indicators and pattern flags, it evaluates every condition combination
that was generated by the search-space module and records where those
conditions fire together.

The module is intentionally written to be explicit and predictable. Each
condition is converted into a callable evaluator once, then all combinations are
checked against the dataframe using boolean masks rather than Python loops over
individual rows.
"""

import operator as _op
import os
import sys
import time
import resource
from typing import Any

import pandas as pd

from .queue_storage import WorkQueue
from .search_space import ConditionCombo, describe_combo

# ── Operator map ────────────────────────────────────────────────────────────
_OPS: dict = {
    "<":  _op.lt,
    "<=": _op.le,
    ">":  _op.gt,
    ">=": _op.ge,
    "==": _op.eq,
    "!=": _op.ne,
}

_ARITH_OPS: dict = {
    "+":  _op.add,
    "-":  _op.sub,
    "*":  _op.mul,
    "/":  _op.truediv,
}


def _resolve_operand(df: pd.DataFrame, value: Any) -> pd.Series | None:
    """Resolve a column name or a literal value into a pandas Series."""
    if isinstance(value, str):
        return df[value] if value in df.columns else None
    return pd.Series(value, index=df.index)


def _get_memory_usage_percent() -> float:
    """Best-effort memory usage estimate for the current process."""
    try:
        import psutil
    except ImportError:  # pragma: no cover
        psutil = None

    if psutil is not None:
        try:
            return float(psutil.Process().memory_percent())
        except Exception:  # pragma: no cover
            try:
                return float(psutil.virtual_memory().percent)
            except Exception:  # pragma: no cover
                pass

    try:
        rss_kb = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        rss_bytes = rss_kb * 1024
        total_bytes = None
        try:
            total_bytes = os.sysconf("SC_PAGE_SIZE") * os.sysconf("SC_PHYS_PAGES")
        except (AttributeError, ValueError, OSError):
            total_bytes = None

        if total_bytes and total_bytes > 0:
            return min(100.0, max(0.0, (rss_bytes / total_bytes) * 100.0))
    except Exception:  # pragma: no cover
        pass

    try:
        with open("/proc/self/status", "r", encoding="utf-8") as handle:
            for line in handle:
                if line.startswith("VmRSS:"):
                    rss_kb = int(line.split()[1])
                    with open("/proc/meminfo", "r", encoding="utf-8") as meminfo:
                        for mem_line in meminfo:
                            if mem_line.startswith("MemTotal:"):
                                total_kb = int(mem_line.split()[1])
                                if total_kb > 0:
                                    return min(100.0, max(0.0, (rss_kb / total_kb) * 100.0))
                    break
    except Exception:  # pragma: no cover
        pass

    return 100.0


# ── Build a lookup: condition name → callable(df) → bool Series ─────────────

def _build_evaluators(payload: dict) -> dict[str, Any]:
    """Pre-compile condition definitions into fast dataframe evaluators.

    Purpose:
        Convert the declarative condition definitions from the payload into
        callable functions that can evaluate a dataframe efficiently.

    Inputs:
        payload: Configuration that contains the list of condition definitions.

    Outputs:
        A dictionary mapping condition names to evaluator callables.

    Supported condition types:
        threshold: compare a column against a scalar value.
        cross: compare two columns directly.
        ratio: compare a column against a scaled version of another column.

    Time complexity:
        O(c) where c is the number of conditions in the payload.
    """
    evaluators = {}

    for cdef in payload["conditions"]:
        name = cdef["name"]
        col  = cdef["col"]
        op   = cdef["op"]
        ctype = cdef.get("type", "threshold")

        if ctype == "threshold":
            if op not in _OPS:
                raise ValueError(f"Unsupported threshold operator {op!r} in '{name}'")
            fn = _OPS[op]
            val = cdef["val"]
            evaluators[name] = lambda df, c=col, f=fn, v=val: (
                pd.Series(False, index=df.index)
                if _resolve_operand(df, c) is None
                else f(_resolve_operand(df, c), v)
            )

        elif ctype == "cross":
            if op not in _OPS:
                raise ValueError(f"Unsupported cross operator {op!r} in '{name}'")
            fn = _OPS[op]
            col2 = cdef["col2"]
            evaluators[name] = lambda df, c=col, f=fn, c2=col2: (
                pd.Series(False, index=df.index)
                if _resolve_operand(df, c) is None or _resolve_operand(df, c2) is None
                else f(_resolve_operand(df, c), _resolve_operand(df, c2))
            )

        elif ctype == "ratio":
            col2   = cdef["col2"]
            factor = cdef.get("factor", 1.0)
            if op in _OPS:
                fn = _OPS[op]
                evaluators[name] = lambda df, c=col, f=fn, c2=col2, fc=factor: (
                    pd.Series(False, index=df.index)
                    if _resolve_operand(df, c) is None or _resolve_operand(df, c2) is None
                    else f(_resolve_operand(df, c), _resolve_operand(df, c2) * fc)
                )
            elif op in _ARITH_OPS:
                fn = _ARITH_OPS[op]
                evaluators[name] = lambda df, c=col, f=fn, c2=col2, fc=factor: (
                    pd.Series(False, index=df.index)
                    if _resolve_operand(df, c) is None or _resolve_operand(df, c2) is None
                    else _op.lt(f(_resolve_operand(df, c), _resolve_operand(df, c2)), fc)
                )
            else:
                raise ValueError(f"Unsupported ratio operator {op!r} in '{name}'")

        else:
            raise ValueError(f"Unknown condition type: {ctype!r} in '{name}'")

    return evaluators


def apply_combo(
    df: pd.DataFrame,
    combo: ConditionCombo,
    evaluators: dict,
) -> pd.Series:
    """Evaluate one combination and return a boolean mask for matches.

    Purpose:
        Determine the rows where every condition in the combination is true at the
        same time.

    Inputs:
        df: Enriched dataframe.
        combo: Tuple of condition names.
        evaluators: Mapping from condition name to evaluator function.

    Outputs:
        A boolean Series with True where the full combination is satisfied.

    Side effects:
        None.

    Algorithm:
        The function starts with an all-True mask and intersects it with the mask
        from each condition. If the mask becomes all False early, evaluation stops
        to save work.
    """
    mask = pd.Series(True, index=df.index)
    for name in combo:
        mask = mask & evaluators[name](df)
        if not mask.any():      # short-circuit: already all False
            break
    return mask


def _iter_combos(combos: list[ConditionCombo] | WorkQueue) -> Any:
    if isinstance(combos, WorkQueue):
        while True:
            batch = combos.get_many(1000)
            if not batch:
                break
            for combo in batch:
                yield combo
        return

    for combo in combos:
        yield combo


def scan_all_combos(
    df: pd.DataFrame,
    combos: list[ConditionCombo] | WorkQueue,
    payload: dict,
) -> list[dict]:
    """Evaluate every generated combo across the full dataframe.

    Purpose:
        Run the brute-force scan that finds candidate condition combinations that
        fire frequently enough to merit further analysis.

    Inputs:
        df: Enriched dataframe.
        combos: The list of condition combinations to evaluate.
        payload: Analysis configuration including min_samples and condition
            definitions.

    Outputs:
        A list of candidate records. Each record contains the condition tuple,
        a human-readable label, the matching row indices, and the total match
        count.

    Side effects:
        Prints a progress indicator while scanning.

    Algorithm:
        The function evaluates each combination once, stores the row positions
        where the combination was true, and keeps only those who pass the minimum
        sample threshold. This is the main filtering step before the reaction
        measurement stage.

    Time complexity:
        O(number_of_combinations * n) in the worst case.

    Memory complexity:
        O(number_of_matches) because only the match positions for surviving
        combinations are kept.
    """
    evaluators  = _build_evaluators(payload)
    min_samples = payload.get("min_samples", 30)
    total       = combos.size() if hasattr(combos, "size") else len(combos)
    results     = []
    threshold   = payload.get("memory_spill_threshold_percent", 80)
    last_check  = 0.0

    for i, combo in enumerate(_iter_combos(combos), 1):
        if i % 1000 == 0 or i == total:
            pct = i / total * 100
            print(f"\r  [{i:>6}/{total}] {pct:5.1f}%  candidates so far: {len(results)}", end="", flush=True)

        now = time.time()
        if now - last_check >= 0.5:
            last_check = now
            if _get_memory_usage_percent() >= threshold:
                pass

        mask        = apply_combo(df, combo, evaluators)
        match_count = int(mask.sum())

        if match_count < min_samples:
            continue

        results.append({
            "combo":       combo,
            "label":       describe_combo(combo),
            "match_index": df.index[mask],
            "match_count": match_count,
        })

    print()  # newline after progress bar
    return results