"""Consistency and frequency filtering for the analysis pipeline.

This module is responsible for the first statistical pruning stage. After price
reactions have been measured, it removes candidates that are either too weakly
directional, too noisy in magnitude, or too rare in the overall sample to be
considered reliable.
"""

import numpy as np
import pandas as pd


def diagnose_thresholds(
    enriched: list[dict],
) -> None:
    """Print percentile diagnostics before the consistency filter runs.

    Purpose:
        Show how the measured candidates are distributed across key statistics so
        the operator can choose sensible thresholds.

    Inputs:
        enriched: List of reaction summaries generated by measure_reactions.

    Outputs:
        None; prints to stdout.
    """

    dir_pcts = [
        max(m["bull_pct"], m["bear_pct"])
        for m in enriched
    ]

    mag_means = [
        m["mag_atr_mean"]
        for m in enriched
        if m.get("mag_atr_mean")
    ]

    mag_cvs = [
        m["mag_atr_std"] / m["mag_atr_mean"]
        for m in enriched
        if (
            m.get("mag_atr_mean")
            and m["mag_atr_mean"] > 0
            and m.get("mag_atr_std") is not None
        )
    ]

    counts = [m["valid_count"] for m in enriched]

    def _pct(label, arr):
        a = np.array(arr, dtype=float)

        print(f"\n  {label} (n={len(a)})")

        if len(a) == 0:
            print("    p10  = n/a")
            print("    p25  = n/a")
            print("    p50  = n/a")
            print("    p75  = n/a")
            print("    p90  = n/a")
            print("    p95  = n/a")
            print("    p99  = n/a")
            print("    max=n/a min=n/a")
            return

        for p in [10, 25, 50, 75, 90, 95, 99]:
            print(f"    p{p:<3} = {np.percentile(a, p):.4f}")

        print(f"    max={a.max():.4f} min={a.min():.4f}")

    print("\n" + "=" * 55)
    print("THRESHOLD DIAGNOSTICS")
    print("=" * 55)

    _pct("Direction %", dir_pcts)
    _pct("Mag ATR mean", mag_means)
    _pct("Mag CV", mag_cvs)
    _pct("Match count", counts)

    print()


def run_consistency_filter(
    enriched: list[dict],
    payload: dict,
    total_candles: int,
) -> list[dict]:
    """Filter candidates by directionality, magnitude variability, and frequency.

    Purpose:
        Keep only candidates that are statistically stable enough to justify
        further validation.

    Inputs:
        enriched: Reaction summaries returned by measure_reactions.
        payload: Configuration containing the filtering thresholds.
        total_candles: Total number of candles in the dataframe.

    Outputs:
        A filtered list of candidate dictionaries with derived consistency fields.

    Side effects:
        None.

    Algorithm:
        For each candidate:
        1. Evaluate the dominant direction percentage, which is the larger of
           bull_pct and bear_pct.
        2. Compute a magnitude coefficient of variation, CV = std / mean, to
           penalise volatile reaction amplitudes.
        3. Compute the candidate frequency as a percentage of the full dataset.
        4. Reject the candidate if any of these metrics fall outside the allowed
           thresholds.

    Why these limits exist:
        They prevent the pipeline from surfacing noisy or one-off conditions that
        happen to have a few large moves but do not recur reliably.

    Time complexity:
        O(m) over the number of enriched candidates.
    """
    min_dir_pct = payload.get("min_direction_pct", 55.0)
    max_mag_cv = payload.get("max_mag_cv", 0.85)
    min_freq_pct = payload.get("min_freq_pct", 0.05)
    max_freq_pct = payload.get("max_freq_pct", 5.0)

    passed = []

    for m in enriched:
        # Directional consistency: the larger of bull_pct and bear_pct.
        dir_pct = max(m["bull_pct"], m["bear_pct"])

        # Frequency is reported as the number of matches divided by the full
        # dataset size, converted to a percentage.
        freq_pct = (
            m["valid_count"] / total_candles * 100
            if total_candles
            else None
        )

        # Step 7A: require a minimum dominant direction percentage.
        # Removing this filter would allow weakly directional patterns to survive.
        if dir_pct < min_dir_pct:
            continue

        # Step 7B: require magnitude consistency. A large CV means the reactions
        # are erratic and therefore less trustworthy.
        mean = m.get("mag_atr_mean") or 0
        std = m.get("mag_atr_std") or 0
        cv = std / mean if mean > 0 else np.nan

        if not np.isnan(cv) and cv > max_mag_cv:
            continue

        # Step 8: require the pattern to appear often enough, but not so often
        # that it becomes trivial or overly common.
        if freq_pct is not None:
            if freq_pct < min_freq_pct:
                continue
            if freq_pct > max_freq_pct:
                continue

        passed.append(
            {
                **m,
                "dir_consistency": round(dir_pct, 2),
                "mag_cv": round(cv, 4) if not np.isnan(cv) else None,
                "freq_pct": round(freq_pct, 4) if freq_pct is not None else None,
            }
        )

    return passed